"""Spider-dex: what you can discover in the box, with real facts for every species."""

FACTS = {
    "house_spider": "Once listed as the fastest spider (≈0.5 m/s). Males roam houses in late summer looking for females.",
    "cellar_spider": "A spider-eater: invades other webs and plucks them like trapped prey. Whirls its body into a blur when threatened.",
    "wolf_spider": "Mothers drag their egg sac on their spinnerets, then carry up to 100 spiderlings on their back.",
    "garden_cross": "Eats its orb web and spins a fresh one most nights; about a quarter of males are eaten while mating.",
    "zebra_jumper": "Its big front eyes give it some of the sharpest vision of any invertebrate — it watches you back.",
    "crab_spider": "Waits on flowers with its front legs spread like arms; females can change between white and yellow.",
    "black_widow": "Its venom (α-latrotoxin) is among the most potent of any spider; the red hourglass is on its belly.",
    "huntsman": "Legs twist sideways so it can run flat against walls — and sideways, crab-fashion, at great speed.",
    "wasp_spider": "Weaves a zig-zag silk band (stabilimentum) into its web; around 80% of males are eaten after mating.",
    "spitting_spider": "Spits two zig-zag streams of venomous glue at up to 28 m/s to pin its prey down.",
    "redknee_tarantula": "Flicks barbed urticating hairs off its abdomen with its back legs when threatened.",
    "golden_orb": "Its silk really is golden, and strong enough to hold small birds; tiny males live on the female's web.",
    "spiny_orb": "Wider than it is long, armoured with six spines — it decorates its web with white silk tufts.",
    "ant_mimic": "Walks a zig-zag ant trail and waves its front legs like antennae; predators that avoid ants avoid it.",
    "regal_jumper": "Its fangs (chelicerae) flash iridescent green; one of the largest jumping spiders in North America.",
    "ladybird_spider": "Males wear ladybird colours as a warning; females live in silk-lined burrows.",
    "net_caster": "Has the largest simple eyes of any spider and throws a silk net held between its front legs.",
    "trapdoor_spider": "Lies in wait under a hinged silk door, feeling for prey through trip-lines fanning out from it.",
    "wandering_spider": "Rears up with its front legs raised and sways when threatened — among the most venomous spiders.",
    "bird_dropping": "Looks — and smells — like a fresh bird dropping, which flies come to land on.",
    "bagheera": "The only known mostly-vegetarian spider: it steals nutritious Beltian bodies from acacia ants.",
    "goliath_birdeater": "The world's heaviest spider (up to 175 g). It can hiss by rubbing bristles on its legs.",
    "peacock_spider": "Males raise a rainbow fan and dance, waving their third pair of legs, to court females.",
    "gooty_sapphire": "A metallic-blue tarantula found in a single small forest area in India — critically endangered.",
    "mirror_spider": "Its abdomen is tiled with silver guanine plates that shrink in seconds when it is disturbed.",
    "golden_wheel": "Escapes wasps by flipping on its side and cartwheeling down sand dunes at 20+ turns a second.",
    "flower_crab": "Shaped and coloured like a flower — and its UV pattern lures bees even with no flowers around.",
    "bolas_spider": "Hunts moths at night by swinging a single sticky glob on a line, baited with moth scent.",
    "diving_bell": "Lives underwater in an air bubble it spins a silk bell around — the only fully aquatic spider.",
    "social_spider": "Lives in colonies of hundreds that build one web, hunt together and raise young together.",
    "dewdrop_spider": "A kleptoparasite: lives on the edges of big orb webs and steals the owner's prey.",
    "nursery_web": "Males court with a silk-wrapped insect as a gift; females guard their young in a silk nursery tent.",
}

# behaviours to witness: (id, label, words that reveal it in the journal)
BEHAVIOURS = [
    ("orb", "An orb web spun", ("finished an orb web",)),
    ("renew", "A web eaten and rebuilt", ("ate the old web",)),
    ("kill", "A spider eating a spider", ("killed and ate",)),
    ("cannibal", "A female eating her mate", ("ate her mate",)),
    ("mate", "Mating", ("mated",)),
    ("gift", "A wedding gift", ("wedding gift", "accepted")),
    ("egg", "An egg sac", ("laid an egg sac",)),
    ("hatch", "Spiderlings hatching", ("spiderlings hatched",)),
    ("brood", "A mother carrying her young", ("climbed onto",)),
    ("tent", "A nursery tent", ("nursery tent",)),
    ("molt", "Molting into an adult", ("molted into an adult",)),
    ("lure", "Aggressive mimicry", ("plucks",)),
    ("theft", "Prey stolen", ("stole a",)),
    ("swarm", "A social swarm", ("swarm a",)),
    ("bolas", "A bolas catch", ("bolas",)),
    ("net", "A net cast", ("dropped its net",)),
    ("trapdoor", "A trapdoor ambush", ("burst out",)),
    ("flower", "A flower ambush", ("ambushed a bee", "lured in a bee")),
    ("wasp", "The tarantula hawk", ("tarantula hawk",)),
    ("ants", "An ant trail", ("trail of ants",)),
    ("rain", "Webs after rain", ("glitter with droplets",)),
    ("dragonfly", "A dragonfly smashing a web", ("dragonfly tore",)),
    ("oldage", "A life complete", ("died of old age",)),
]
